#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

BOLT_PATH="${BOLT_PATH:-/var/lib/chronograf/chronograf-v1.db}";
CANNED_PATH="${CANNED_PATH:-/usr/share/chronograf/canned}";
RESOURCES_PATH="${RESOURCES_PATH:-/usr/share/chronograf/resources}";

vecho "Ensure configuration directories exist";
mkdir -p \
    $(dirname ${BOLT_PATH}) \
    ${CANNED_PATH} \
    ${RESOURCES_PATH} \
    ;

# fix permissions
if [ -z "${CHRONOGRAF_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R ${S6_USER:-alpine}:${PGID:-1000} \
        $(dirname ${BOLT_PATH}) \
        ${CANNED_PATH} \
        ${RESOURCES_PATH} \
        ;
fi;
