#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

# CHRONOGRAF_ARGS="${CHRONOGRAF_ARGS:-}";
# no arguments passed by default, use environment vars instead

usercmd \
exec \
    /usr/bin/chronograf \
    ${CHRONOGRAF_ARGS} \
    ;
